sudo: required
language: node_js
before_install:
  - 'wget https://frankl.in/u/vnstat_bin.tar'
  - 'tar xvf vnstat_bin.tar'
  - 'sudo ./vnstatd -d'
  - 'sudo ./vnstat -u -i $NODE_APP_IFACE'
  - 'sudo cp -v ./vnstat /usr/bin/'
node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'
 